settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: example_org
    name: example.org
    url: 'https://example.org'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: debug_webhook_site
    name: DEBUG.webhook.site
    url: 'https://webhook.site/fd544088-f85f-45fa-b0e1-b6c4db1e9430'
    method: GET
    expectStatus: 200
    followRedirect: true

  - id: debug_recursive_workers_dev
    name: DEBUG.cf-workers-status-page-production.cloudflare3125.workers.dev
    url: 'https://cf-workers-status-page-production.cloudflare3125.workers.dev'
    method: GET
    expectStatus: 200
    followRedirect: true
